name: Test loading a value into artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'LICENSE'
      - '.github/*'

jobs:
  load-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Pull Request Branch
        id: get_branch
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          BRANCH_NAME=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
            | jq --raw-output .head.ref)
          echo "Pull Request Branch: $BRANCH_NAME"

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

      - name: test
        run: |
          echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"

      - uses: tonynguyenit18/github-action-custom-vars@v1

      - run: echo $RECENT_MERGED_BRANCH_NAME

      - name: Retrieve value from cache
        uses: actions/cache@v3
        id: cache
        with:
          key: message-id-${{ env.RECENT_MERGED_BRANCH_NAME }}
          path: message-id.txt

      - name: Use retrieved value
        run: |
          echo "Retrieved value: ${{ steps.cache.outputs.cache-hit }}"
