name: Test loading a value into artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'LICENSE'
      - '.github/*'

jobs:
  load-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: read
    steps:

      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

      - name: test
        run: |
          echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"

      - name: Retrieve value from artifact
        uses: actions/download-artifact@v3
        id: cache
        with:
          name: message-id-${{ steps.PR.outputs.number }}
          path: message-id.txt

      - name: Use retrieved value
        run: |
          value=$(cat message-id.txt)
          echo "Retrieved value: $value"
