name: Test loading a value into artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'LICENSE'
      - '.github/*'

jobs:
  load-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get pull request number and branch name
        id: branch-name
        run: |
          COMMIT_HASH=${{ github.sha }}
          REPO=${{ github.repository }}

          PULL_REQUEST_NUMBER=$(curl -s "https://api.github.com/repos/$REPO/commits/$COMMIT_HASH/pulls" \
            | jq -r '.[0].number')
          BRANCH_NAME=$(curl -s "https://api.github.com/repos/$REPO/commits/$COMMIT_HASH" \
            | jq -r '.commit.tree.sha')

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT


      - uses: tonynguyenit18/github-action-custom-vars@v1
      - run: echo $RECENT_MERGED_BRANCH_NAME

      - name: Retrieve value from cache
        uses: actions/cache@v3
        id: cache
        with:
          key: message-id-${{ steps.branch-name.outputs.branch_name }}
          path: message-id.txt

      - name: Use retrieved value
        run: |
          echo "Retrieved value: ${{ steps.cache.outputs.cache-hit }}"
