name: Test loading a value into artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'LICENSE'
      - '.github/*'

jobs:
  load-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Use value from cache
        uses: actions/cache@v3
        with:
          key: message-id-${{ github.head_ref }}
          path: message-id.txt

      - name: Retrieve value from cache
        uses: actions/cache@v3
        id: cache
        with:
          key: message-id-${{ github.head_ref }}
          path: message-id.txt

      - name: Use retrieved value
        run: |
          echo "Retrieved value: ${{ steps.cache.outputs.cache-hit }}"
