name: Tag, build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
      - dev
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'LICENSE'
      - '.github/*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine the next tag version and push tag
        id: tag-check
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main,dev,staging
          tag_prefix: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}

      - name: Keep only last 10 tags
        id: delete-tag
        run: |
          for i in `git tag -l --sort=-v:refname | grep ${{ github.ref_name == 'main' && 'production' || github.ref_name }} | tail -n +5`; do \
          echo $i; \
          done
