name: Test saving a value into artifact

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'LICENSE'
      - '.github/*'

jobs:
  save-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set message-id variable
        run: |
          echo "3008984" > message-id.txt

      - name: Save value to cache
        uses: actions/cache@v3
        with:
          key: message-id-${{ github.event.number }}
          path: message-id.txt
